#!/bin/bash

export LANG=C
TELEGRAM_CHAT_ID="ddddddd"
TELEGRAM_BOT_TOKEN="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
LOGGED_USER="$(whoami)"
LOGGED_HOST="$(hostname -f)"
LOGGED_IP="$(echo "$SSH_CONNECTION" | awk '{ print $1 }')"
LOGGED_PORT="$(echo "$SSH_CONNECTION" | awk '{ print $2 }')"
NOW="$(TZ=UTC-3 date +'%b %d %Y %r')"
MESSAGE="$(echo "<strong>SSH Login Notification</strong>\n\nHost: $LOGGED_HOST\nUser: $LOGGED_USER\nIP: $LOGGED_IP:$LOGGED_PORT\nTime: $NOW")"

/usr/bin/curl --silent --output /dev/null \
    --data-urlencode "chat_id=${TELEGRAM_CHAT_ID}" \
    --data-urlencode "text=${MESSAGE}" \
    --data-urlencode "parse_mode=HTML" \
    --data-urlencode "disable_web_page_preview=true" \
    "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage"
